[tool.poetry]
name = "upload_tgbot"
version = "1.5.3"
description = ""
authors = ["Divanshu Chauhan <23524935+Divkix@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Pyrogram = "~=2.0.70"
TgCrypto = "~=1.2.2"
pyromod = {git = "https://github.com/usernein/pyromod.git", rev = "2d71f19a821355ff9a4e1cd9fdbbf2a0990b482a"}
pySmartDL = "~=1.3.4"
beautifulsoup4 = "~=4.10.0"
lxml = "~=4.6.4"
httpx = {version = "~=0.21.1", extras = ["http2"]}
dnspython = "~=2.1.0"
pickleDB = "~=0.9.2"
cachetools = "~=4.2.4"
pycryptodome = "~=3.12.0"
aiofiles = "~=0.8.0"
pymongo = "~=4.0"
prettyconf = "^2.2.1"

[tool.poetry.dev-dependencies]
black = "~=21.12b0"
isort = "~=5.10.1"
pre-commit = "~=2.16.0"
pyclean = "~=2.0.0"
pylint = "~=2.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
